import { firebaseConfigured, ensureSignedIn, observeAuth, googleSignIn, signOutUser, read, write, patch, erase } from './firebase.js';
import { COLORS, validatePuzzle } from './puzzle.js';

const ADMIN_EMAIL = 'dekelhasid@gmail.com';
const $ = selector => document.querySelector(selector);
let editingId = null;
let library = {};
let initialized = false;

function defaultPuzzle() { return { title: '', groups: COLORS.map((color, index) => ({ title: '', description: '', color, words: ['', '', '', ''] })) }; }
function status(text, urgent = false) { const target = $('#draft-state'); target.textContent = text; target.style.background = urgent ? '#f8dfdf' : ''; target.style.color = urgent ? '#8d3030' : ''; }
function renderEditor(puzzle = defaultPuzzle()) {
  $('#puzzle-title-input').value = puzzle.title || ''; const container = $('#groups-editor'); container.replaceChildren();
  puzzle.groups.forEach((group, index) => { const node = $('#group-template').content.cloneNode(true); const card = node.querySelector('.group-card'); card.style.setProperty('--accent', group.color || COLORS[index]); node.querySelector('.group-number').textContent = index + 1; const color = node.querySelector('.group-color'); color.value = group.color || COLORS[index]; color.addEventListener('input', () => card.style.setProperty('--accent', color.value)); node.querySelector('.group-title').value = group.title || ''; node.querySelector('.group-description').value = group.description || ''; const wordInputs = node.querySelector('.word-inputs'); for (let wordIndex = 0; wordIndex < 4; wordIndex += 1) { const label = document.createElement('label'); label.textContent = `מילה ${wordIndex + 1}`; const input = document.createElement('input'); input.className = 'group-word'; input.maxLength = 40; input.value = group.words?.[wordIndex] || ''; label.append(input); wordInputs.append(label); } container.append(node); });
  $('#editor-heading').textContent = editingId ? `עריכת חידה ${editingId}` : 'חידה חדשה'; status(editingId ? 'טיוטה שנבחרה לעריכה' : 'טיוטה חדשה');
}
function readEditor() { return { id: editingId || undefined, title: $('#puzzle-title-input').value.trim(), groups: [...document.querySelectorAll('.group-card')].map(card => ({ title: card.querySelector('.group-title').value.trim(), description: card.querySelector('.group-description').value.trim(), color: card.querySelector('.group-color').value, words: [...card.querySelectorAll('.group-word')].map(input => input.value.trim()) })) }; }
async function saveDraft() { const puzzle = readEditor(); const error = validatePuzzle(puzzle); if (error) return status(error, true); puzzle.updatedAt = new Date().toISOString(); try { await write('games/draft', puzzle); status('הטיוטה נשמרה ב־Firebase'); } catch (error) { localStorage.setItem('mahakesher.draft', JSON.stringify(puzzle)); status('הטיוטה נשמרה בדפדפן — בדקו את Firebase.', true); } }
function newId() { const date = new Date().toISOString().slice(0, 10); return `${date}-${Math.random().toString(36).slice(2, 7)}`; }
async function publish() { const puzzle = readEditor(); const error = validatePuzzle(puzzle); if (error) return status(error, true); const id = editingId || newId(); const now = new Date().toISOString(); const published = { ...puzzle, id, status: 'published', createdAt: library[id]?.createdAt || now, updatedAt: now, publishedAt: now };
  try { await write(`puzzles/${id}`, published); await write('games/currentGameId', id); editingId = id; status('החידה פורסמה והיא החידה הנוכחית.'); await loadLibrary(); } catch (error) { console.error(error); status('הפרסום נכשל. ודאו שחוקי Firebase והחשבון המורשה מוגדרים.', true); }
}
async function loadDraft() { try { const draft = await read('games/draft'); if (draft && !editingId) renderEditor(draft); } catch { const local = localStorage.getItem('mahakesher.draft'); if (local && !editingId) renderEditor(JSON.parse(local)); } }
function itemButton(label, className, handler) { const button = document.createElement('button'); button.className = className; button.type = 'button'; button.textContent = label; button.addEventListener('click', handler); return button; }
function renderLibrary() { const container = $('#puzzle-library'); container.replaceChildren(); const entries = Object.values(library).sort((a, b) => String(b.publishedAt || b.createdAt || '').localeCompare(String(a.publishedAt || a.createdAt || ''))); if (!entries.length) { container.innerHTML = '<p class="empty">עדיין לא פורסמו חידות.</p>'; return; }
  entries.forEach(puzzle => { const item = document.createElement('article'); item.className = 'puzzle-item'; const info = document.createElement('div'); info.innerHTML = `<h3>${escapeHtml(puzzle.title)}</h3><p>${puzzle.id} · ${puzzle.status === 'archived' ? 'בארכיון' : 'פורסמה'}</p>`; const actions = document.createElement('div'); actions.className = 'puzzle-item-actions'; actions.append(itemButton('עריכה', 'secondary', () => { editingId = puzzle.id; renderEditor(puzzle); window.scrollTo({ top: 0, behavior: 'smooth' }); })); actions.append(itemButton('פרסום', 'primary', () => republish(puzzle.id))); actions.append(itemButton('ארכוב', 'secondary', () => archive(puzzle.id))); actions.append(itemButton('שכפול', 'secondary', () => duplicate(puzzle))); actions.append(itemButton('סטטיסטיקה', 'secondary', () => showPuzzleStats(puzzle.id))); actions.append(itemButton('מחיקה', 'danger', () => destroy(puzzle.id, puzzle.title))); item.append(info, actions); container.append(item); }); }
async function republish(id) { if (!confirm('להפוך חידה זו לחידה הנוכחית?')) return; try { await patch(`puzzles/${id}`, { status: 'published', publishedAt: new Date().toISOString() }); await write('games/currentGameId', id); await loadLibrary(); } catch { alert('הפרסום נכשל.'); } }
async function archive(id) { if ((await read('games/currentGameId')) === id) { alert('אי אפשר לארכב את החידה הנוכחית. פרסמו תחילה חידה אחרת.'); return; } if (!confirm('לארכב את החידה? היא לא תימחק.')) return; try { await patch(`puzzles/${id}`, { status: 'archived', archivedAt: new Date().toISOString() }); await loadLibrary(); } catch { alert('הארכוב נכשל.'); } }
function duplicate(puzzle) { editingId = null; renderEditor({ ...puzzle, title: `${puzzle.title} — עותק`, groups: puzzle.groups.map(group => ({ ...group, words: [...group.words] })) }); window.scrollTo({ top: 0, behavior: 'smooth' }); }
async function destroy(id, title) { if (!confirm(`למחוק לצמיתות את „${title}”?`)) return; try { await erase(`puzzles/${id}`); if ((await read('games/currentGameId')) === id) await write('games/currentGameId', null); if (editingId === id) { editingId = null; renderEditor(); } await loadLibrary(); } catch { alert('המחיקה נכשלה.'); } }
async function showPuzzleStats(id) { try { const stats = Object.values((await read(`stats/${id}`)) || {}); const finished = stats.filter(item => item.finished && item.playerKind === 'named'); const solved = finished.filter(item => item.solved).length; alert(`סטטיסטיקה לחידה ${id}\n${finished.length} שחקנים מזוהים סיימו\n${solved} פתרו בהצלחה`); } catch { alert('לא ניתן לטעון סטטיסטיקה.'); } }
async function loadPlayers() { const target = $('#players-library'); target.replaceChildren(); try { const players = Object.values((await read('players')) || {}).sort((a, b) => (b.streak || 0) - (a.streak || 0)); if (!players.length) { target.innerHTML = '<p class="empty">עדיין אין שחקנים שמורים.</p>'; return; } players.forEach(player => { const games = Object.values(player.games || {}); const item = document.createElement('article'); item.className = 'puzzle-item'; item.innerHTML = `<div><h3>${escapeHtml(player.name)}</h3><p>${games.length} חידות · רצף נוכחי: ${player.streak || 0}</p></div>`; target.append(item); }); } catch { target.innerHTML = '<p class="empty">לא ניתן לטעון שחקנים.</p>'; } }
async function loadLibrary() { try { library = (await read('puzzles')) || {}; renderLibrary(); await loadPlayers(); } catch { $('#puzzle-library').innerHTML = '<p class="empty">לא ניתן לטעון חידות.</p>'; } }
function escapeHtml(value) { return String(value || '').replace(/[&<>'"]/g, char => ({ '&':'&amp;', '<':'&lt;', '>':'&gt;', "'":'&#39;', '"':'&quot;' }[char])); }
function isAdmin(user) { return user?.email?.toLowerCase() === ADMIN_EMAIL && user.emailVerified; }
function bind() { $('#auth-button').addEventListener('click', async () => { try { if ($('#auth-button').dataset.signedin === 'true') await signOutUser(); else await googleSignIn(); } catch (error) { alert(`לא ניתן להתחבר: ${error.message}`); } }); $('#save-draft').addEventListener('click', saveDraft); $('#publish-puzzle').addEventListener('click', publish); $('#new-puzzle').addEventListener('click', () => { editingId = null; renderEditor(); }); $('#refresh-library').addEventListener('click', loadLibrary); }
async function init() { bind(); if (!firebaseConfigured) { $('#auth-button').hidden = true; $('#access-notice').innerHTML = '<h1>Firebase עדיין לא מוגדר</h1><p>מלאו את <code>js/firebase-config.js</code> בפרטי Web App של Firebase, הפעילו Google ו־Anonymous Authentication, ואז מסך הניהול יהיה זמין לחשבון המורשה.</p>'; return; } await ensureSignedIn(); observeAuth(async user => { const allowed = isAdmin(user); $('#admin-content').hidden = !allowed; $('#access-notice').hidden = allowed; $('#auth-button').dataset.signedin = String(allowed); $('#auth-button').textContent = allowed ? 'התנתקות' : 'התחברות Google'; if (!allowed) { $('#access-notice').innerHTML = '<h1>ניהול חידות</h1><p>יש להתחבר עם <strong>dekelhasid@gmail.com</strong> כדי לערוך ולפרסם חידות.</p>'; return; } if (!initialized) { initialized = true; renderEditor(); await loadDraft(); await loadLibrary(); } }); }
init();
