// Canonical clean copy — replace the entire GitHub file with this file's contents.
import { firebaseConfigured, firebaseAuth, ensureSignedIn, observeAuth, signOutUser, read, write, patch, erase } from './firebase.js';
import { signInWithEmailAndPassword } from 'https://www.gstatic.com/firebasejs/10.12.4/firebase-auth.js';
import { COLORS, CURRENT_PUZZLE, validatePuzzle } from './puzzle.js';

const ADMIN_EMAIL = 'admin@mahakesher2nekuda0.com';
const DEVELOPMENT_MODE = false;
const $ = selector => document.querySelector(selector);
let editingId = null;
let library = {};
let initialized = false;

function defaultPuzzle() { return { title: '', hint: { words: ['', ''] }, groups: COLORS.map((color, index) => ({ title: '', color, words: ['', '', '', ''] })) }; }
function status(text, urgent = false) { const target = $('#draft-state'); target.textContent = text; target.style.background = urgent ? '#f8dfdf' : ''; target.style.color = urgent ? '#8d3030' : ''; }
function firebaseFailure(error) { const detail = String(error?.code || error?.message || 'unknown'); if (detail.includes('PERMISSION_DENIED') || detail.includes('permission-denied')) return 'Firebase דחה את הכתיבה. בדקו שהכללים פורסמו ושנכנסתם עם חשבון המנהל.'; if (detail.includes('not-signed-in')) return 'לא נמצאה התחברות מנהל פעילה. התנתקו והתחברו שוב.'; if (detail.includes('network-request-failed')) return 'לא נוצר חיבור ל־Firebase. בדקו את ה־API key ואת החיבור לרשת.'; if (detail.includes('api-key-not-valid')) return 'ה־API key של Firebase אינו תקין או אינו פעיל.'; return `Firebase לא שמר את הטיוטה: ${detail}`; }
function renderPuzzleHint(puzzle) { let area = $('#puzzle-hint-fields'); if (!area) { area = document.createElement('div'); area.id = 'puzzle-hint-fields'; area.style.cssText = 'display:grid;grid-template-columns:1fr 1fr;gap:12px;margin-top:16px'; const createLabel = (labelText, inputId) => { const label = document.createElement('label'); label.className = 'wide-label'; label.textContent = labelText; const input = document.createElement('input'); input.id = inputId; input.maxLength = 40; input.setAttribute('list', 'puzzle-word-options'); input.placeholder = 'הקלידו מילה מהחידה'; label.append(input); return label; }; const options = document.createElement('datalist'); options.id = 'puzzle-word-options'; area.append(createLabel('מילת רמז 1', 'puzzle-hint-word-1'), createLabel('מילת רמז 2', 'puzzle-hint-word-2'), options); $('#puzzle-title-input').closest('label').after(area); } const options = $('#puzzle-word-options'); options.replaceChildren(); puzzle.groups.flatMap(group => group.words || []).filter(Boolean).forEach(word => { const option = document.createElement('option'); option.value = word; options.append(option); }); const legacyWords = Number.isInteger(puzzle.hint?.groupIndex) ? puzzle.groups[puzzle.hint.groupIndex]?.words?.slice(0, 2) : null; const words = puzzle.hint?.words || legacyWords || ['', '']; $('#puzzle-hint-word-1').value = words[0] || ''; $('#puzzle-hint-word-2').value = words[1] || ''; }
function renderEditor(puzzle = defaultPuzzle()) {
  $('#puzzle-title-input').value = puzzle.title || ''; renderPuzzleHint(puzzle); const container = $('#groups-editor'); container.replaceChildren();
  puzzle.groups.forEach((group, index) => { const node = $('#group-template').content.cloneNode(true); const card = node.querySelector('.group-card'); card.style.setProperty('--accent', group.color || COLORS[index]); node.querySelector('.group-number').textContent = index + 1; const color = node.querySelector('.group-color'); color.value = group.color || COLORS[index]; color.addEventListener('input', () => card.style.setProperty('--accent', color.value)); node.querySelector('.group-title').value = group.title || ''; const obsoleteHint = node.querySelector('.group-hint') || node.querySelector('.group-description'); if (obsoleteHint) obsoleteHint.closest('label').remove(); const wordInputs = node.querySelector('.word-inputs'); for (let wordIndex = 0; wordIndex < 4; wordIndex += 1) { const label = document.createElement('label'); label.textContent = `מילה ${wordIndex + 1}`; const input = document.createElement('input'); input.className = 'group-word'; input.maxLength = 40; input.value = group.words?.[wordIndex] || ''; label.append(input); wordInputs.append(label); } container.append(node); });
  $('#editor-heading').textContent = editingId ? `עריכת חידה ${editingId}` : 'חידה חדשה'; status(editingId ? 'טיוטה שנבחרה לעריכה' : 'טיוטה חדשה');
}
function readEditor() { return { id: editingId || undefined, title: $('#puzzle-title-input').value.trim(), hint: { words: [$('#puzzle-hint-word-1').value.trim(), $('#puzzle-hint-word-2').value.trim()] }, groups: [...document.querySelectorAll('.group-card')].map(card => ({ title: card.querySelector('.group-title').value.trim(), color: card.querySelector('.group-color').value, words: [...card.querySelectorAll('.group-word')].map(input => input.value.trim()) })) }; }
async function saveDraft() { const puzzle = readEditor(); const error = validatePuzzle(puzzle); if (error) return status(error, true); puzzle.updatedAt = new Date().toISOString(); try { if (!firebaseAuth()?.currentUser) throw new Error('not-signed-in'); const saved = await write('games/draft', puzzle); if (!saved) throw new Error('firebase-not-configured'); status('הטיוטה נשמרה ב־Firebase'); } catch (error) { console.error(error); status(firebaseFailure(error), true); } }
function newId() { const date = new Date().toISOString().slice(0, 10); return `${date}-${Math.random().toString(36).slice(2, 7)}`; }
async function publish() { const puzzle = readEditor(); const error = validatePuzzle(puzzle); if (error) return status(error, true); const id = editingId || newId(); const now = new Date().toISOString(); const published = { ...puzzle, id, status: 'published', createdAt: library[id]?.createdAt || now, updatedAt: now, publishedAt: now };
  try { if (!firebaseAuth()?.currentUser) throw new Error('not-signed-in'); const puzzleSaved = await write(`puzzles/${id}`, published); const currentGameSaved = await write('games/currentGameId', id); if (!puzzleSaved || !currentGameSaved) throw new Error('firebase-not-configured'); editingId = id; status('החידה פורסמה והיא החידה הנוכחית.'); await loadLibrary(); } catch (error) { console.error(error); status(firebaseFailure(error), true); }
}
async function loadDraft() { try { const draft = await read('games/draft'); if (draft && !editingId) renderEditor(draft); } catch (error) { console.warn('Could not load Firebase draft.', error); } }
function itemButton(label, className, handler) { const button = document.createElement('button'); button.className = className; button.type = 'button'; button.textContent = label; button.addEventListener('click', handler); return button; }
function renderLibrary() { const container = $('#puzzle-library'); container.replaceChildren(); const entries = Object.values(library).sort((a, b) => String(b.publishedAt || b.createdAt || '').localeCompare(String(a.publishedAt || a.createdAt || ''))); if (!entries.length) { container.innerHTML = '<p class="empty">עדיין לא פורסמו חידות.</p>'; return; }
  entries.forEach(puzzle => { const item = document.createElement('article'); item.className = 'puzzle-item'; const info = document.createElement('div'); info.innerHTML = `<h3>${escapeHtml(puzzle.title)}</h3><p>${puzzle.id} · ${puzzle.status === 'archived' ? 'בארכיון' : 'פורסמה'}</p>`; const actions = document.createElement('div'); actions.className = 'puzzle-item-actions'; actions.append(itemButton('עריכה', 'secondary', () => { editingId = puzzle.id; renderEditor(puzzle); window.scrollTo({ top: 0, behavior: 'smooth' }); })); actions.append(itemButton('פרסום', 'primary', () => republish(puzzle.id))); actions.append(itemButton('ארכוב', 'secondary', () => archive(puzzle.id))); actions.append(itemButton('שכפול', 'secondary', () => duplicate(puzzle))); actions.append(itemButton('סטטיסטיקה', 'secondary', () => showPuzzleStats(puzzle.id))); actions.append(itemButton('מחיקה', 'danger', () => destroy(puzzle.id, puzzle.title))); item.append(info, actions); container.append(item); }); }
async function republish(id) { if (!confirm('להפוך חידה זו לחידה הנוכחית?')) return; try { await patch(`puzzles/${id}`, { status: 'published', publishedAt: new Date().toISOString() }); await write('games/currentGameId', id); await loadLibrary(); } catch { alert('הפרסום נכשל.'); } }
async function archive(id) { if ((await read('games/currentGameId')) === id) { alert('אי אפשר לארכב את החידה הנוכחית. פרסמו תחילה חידה אחרת.'); return; } if (!confirm('לארכב את החידה? היא לא תימחק.')) return; try { await patch(`puzzles/${id}`, { status: 'archived', archivedAt: new Date().toISOString() }); await loadLibrary(); } catch { alert('הארכוב נכשל.'); } }
function duplicate(puzzle) { editingId = null; renderEditor({ ...puzzle, title: `${puzzle.title} — עותק`, groups: puzzle.groups.map(group => ({ ...group, words: [...group.words] })) }); window.scrollTo({ top: 0, behavior: 'smooth' }); }
async function destroy(id, title) { if (!confirm(`למחוק לצמיתות את „${title}”?`)) return; try { await erase(`puzzles/${id}`); if ((await read('games/currentGameId')) === id) await write('games/currentGameId', null); if (editingId === id) { editingId = null; renderEditor(); } await loadLibrary(); } catch { alert('המחיקה נכשלה.'); } }
async function showPuzzleStats(id) { try { const stats = Object.values((await read(`stats/${id}`)) || {}); const finished = stats.filter(item => item.finished && item.playerKind === 'named'); const solved = finished.filter(item => item.solved).length; alert(`סטטיסטיקה לחידה ${id}\n${finished.length} שחקנים מזוהים סיימו\n${solved} פתרו בהצלחה`); } catch { alert('לא ניתן לטעון סטטיסטיקה.'); } }
async function loadPlayers() { const target = $('#players-library'); target.replaceChildren(); try { const players = Object.values((await read('players')) || {}).sort((a, b) => (b.streak || 0) - (a.streak || 0)); if (!players.length) { target.innerHTML = '<p class="empty">עדיין אין שחקנים שמורים.</p>'; return; } players.forEach(player => { const games = Object.values(player.games || {}); const item = document.createElement('article'); item.className = 'puzzle-item'; item.innerHTML = `<div><h3>${escapeHtml(player.name)}</h3><p>${games.length} חידות · רצף נוכחי: ${player.streak || 0}</p></div>`; target.append(item); }); } catch { target.innerHTML = '<p class="empty">לא ניתן לטעון שחקנים.</p>'; } }
async function loadLibrary() { try { library = (await read('puzzles')) || {}; renderLibrary(); await loadPlayers(); } catch { $('#puzzle-library').innerHTML = '<p class="empty">לא ניתן לטעון חידות.</p>'; } }
function escapeHtml(value) { return String(value || '').replace(/[&<>'"]/g, char => ({ '&':'&amp;', '<':'&lt;', '>':'&gt;', "'":'&#39;', '"':'&quot;' }[char])); }
function isAdmin(user) { return DEVELOPMENT_MODE || user?.email?.toLowerCase() === ADMIN_EMAIL; }
function ensureAuthDialog() { if (!$('#auth-dialog')) document.body.insertAdjacentHTML('beforeend', '<dialog id="auth-dialog" style="width:min(92vw,390px);border:0;border-radius:8px;padding:24px;box-shadow:0 20px 60px #0005"><form id="email-auth-form" method="dialog"><button id="auth-close" type="button" style="position:absolute;left:10px;top:7px;border:0;background:transparent;font-size:24px">×</button><h2 style="margin:0 0 8px">כניסת מנהל</h2><p>הזינו את סיסמת חשבון המנהל כדי לערוך ולפרסם חידות.</p><label style="display:block;font-weight:bold;margin-top:14px">סיסמה<input id="admin-pin" type="password" autocomplete="current-password" required style="display:block;width:100%;padding:10px;margin-top:5px;direction:ltr"></label><p id="auth-error" role="alert" style="color:#a13b3b;min-height:1.3em"></p><button class="primary" type="submit" style="width:100%">כניסה</button></form></dialog>'); const close = $('#auth-close') || document.querySelector('.dialog-close'); if (close && !close.dataset.bound) { close.dataset.bound = 'true'; close.addEventListener('click', () => $('#auth-dialog').close()); } }
function bind() { ensureAuthDialog(); $('#auth-button').addEventListener('click', async () => { try { if ($('#auth-button').dataset.signedin === 'true') await signOutUser(); else { $('#auth-error').textContent = ''; $('#auth-dialog').showModal(); } } catch (error) { alert(`לא ניתן להתנתק: ${error.message}`); } }); $('#email-auth-form').addEventListener('submit', async event => { event.preventDefault(); $('#auth-error').textContent = ''; try { await signInWithEmailAndPassword(firebaseAuth(), ADMIN_EMAIL, $('#admin-pin').value); $('#auth-dialog').close(); } catch (error) { $('#auth-error').textContent = error.code === 'auth/invalid-credential' ? 'קוד הניהול אינו נכון.' : 'לא ניתן להתחבר כרגע. נסו שוב.'; } }); $('#save-draft').addEventListener('click', saveDraft); $('#publish-puzzle').addEventListener('click', () => publish()); $('#new-puzzle').addEventListener('click', () => { editingId = null; renderEditor(); }); $('#refresh-library').addEventListener('click', loadLibrary); }
async function init() { bind(); if (!firebaseConfigured) { $('#auth-button').hidden = true; $('#access-notice').innerHTML = '<h1>Firebase עדיין לא מוגדר</h1><p>מלאו את <code>js/firebase-config.js</code> בפרטי Web App של Firebase והפעילו Email/Password ו־Anonymous Authentication, ואז מסך הניהול יהיה זמין.</p>'; return; } await ensureSignedIn(); observeAuth(async user => { const allowed = isAdmin(user); $('#auth-button').hidden = DEVELOPMENT_MODE; $('#admin-content').hidden = !allowed; $('#access-notice').hidden = allowed; $('#auth-button').dataset.signedin = String(allowed); $('#auth-button').textContent = allowed ? 'התנתקות' : 'כניסת מנהל'; if (!allowed) { $('#access-notice').innerHTML = '<h1>ניהול חידות</h1><p>יש להתחבר עם סיסמת חשבון המנהל כדי לערוך ולפרסם חידות.</p>'; return; } if (!initialized) { initialized = true; renderEditor(CURRENT_PUZZLE); await loadDraft(); await loadLibrary(); } }); }
init();
